name: Renpho to Garmin Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v5

      - name: Python installieren
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Tool von GitHub installieren
        # Hier installieren wir direkt vom Quellcode, da es kein pip-Paket gibt
        run: |
          pip install git+https://github.com/setu-m/renpho-garmin-sync.git

      - name: Sync ausführen
        env:
          RENPHO_EMAIL: ${{ secrets.RENPHO_USER }}
          RENPHO_PASSWORD: ${{ secrets.RENPHO_PASSWORD }}
          GARMIN_EMAIL: ${{ secrets.GARMIN_USER }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: renpho-sync
